### ISSUE TITLE
Support `reserve` like `std::vector<T>::reserve` in C++

### ISSUE THREAD

**Issue by czgdp1807** [lcompilers/lpython#2232] opened 2023-07-30 15:09 UTC
It looks like reserve makes a big difference here, so we should support it in LPython as well. For example by `from lpython import reserve` and just call this function. The CPython implementation will not do anything.

Here is how to use it:
```python
from lpython import reserve
def dijkstra_shortest_path(n: i32, source: i32) -> i32:
    i: i32; j: i32; v: i32; u: i32; mindist: i32; alt: i32; dummy: i32; uidx: i32
    dist_sum: i32;
    graph: list[i32] = []
    dist: list[i32] = []
    reserve(graph, n*n)
```

In CPython emulation this will be an empty function (no-op), in LPython we reserve the memory for this list, similar to reserve in C++, for performance.

_Originally posted by @certik in https://github.com/lcompilers/lpython/issues/2231#issuecomment-1657196590_

**Comment by czgdp1807** [comment] 2023-07-30 15:10
@kabra1110 Please keep it a high priority so that we can benchmark it against equivalent C++ code in https://github.com/lcompilers/lpython/issues/2231.

**Comment by certik** [comment] 2023-07-30 15:10
Duplicate of https://github.com/lcompilers/lpython/issues/2233.

**Closed** 2023-08-01 17:02 UTC
