### ISSUE TITLE
Variable of list[i32] type has unnecessary newline character while printing.

### ISSUE THREAD

**Issue by faze-geek** [lcompilers/lpython#1477] opened 2023-01-29 06:17 UTC
A new line character is encountered before and after the `list[i32] ` type. I checked integers, floats, strings which give expected answers when printed together.
```
def main1():
    a : i32 = 1
    s : str ="abc"
    l : list[i32] = [1,2,3,4,5]
    print(a,l,s)

main1()

(lp) C:\Users\kunni\lpython>python try.py
1 [1, 2, 3, 4, 5] abc

(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
   Creating library try.lib and object try.exp
1
[1, 2, 3, 4, 5]
abc
```

**Comment by certik** [comment] 2023-01-30 14:34
Yes, that's the same issue in LFortran. We need to fix this in ARS->LLVM.

**Comment by anutosh491** [comment] 2023-02-06 07:25
Hello @certik , I'll be interested in fixing this issue , though being relatively new to lpython I haven't been able to figure out where the issue is or what exactly goes wrong . 

There's no problem while printing an integer and say a string together , so I thought of using this as my base . I compared the ASTs, ASRs and LLVM IRs of both programs (printing int and a string and printing int and a list) and the AST/ASRs look relatively similar so I think it's not here where the issue is. Though I don't understand LLVM IRs that well as of now hence can't say if there errors here but yeah they both looked a bit different .

**Comment by Thirumalai-Shaktivel** [comment] 2023-02-07 03:20
@anutosh491 go ahead and start working on this issue.
You can look into `visit_print()` (more precisely `handle_print()`) in `asr_to_llvm.cpp`, which handles the print statement. I think the issue is with the end attribute.

**Comment by anutosh491** [comment] 2023-02-08 05:47
Thanks for the information . I've been looking into it , especially `print_list.cpp` which helps us print lists whenever present in print statements. While going through the documentation for the ASR pass https://github.com/lcompilers/lpython/blob/00ba081f0bf0bb52e9606ba7bfcbfbb0d195ff38/src/libasr/pass/print_list.cpp#L11-L28 , I can see what's going wrong 


These things aren't equivalent is what I realize . Ther first line should be `print(a, b, sep="pqr", end="")` and not `print(a, b, sep="pqr")` because otherwise there will be a newline after printing `a`, `b` which we don't want . So I was somewhat concerned with 2 functions from `print_list.cpp` which are `visit_Print` and `print_list_helper` . The latter one helps us print lists but as of now I don't think we're printing the list wrongly ... so I guess something needs to be done in the `visit_Print` function . 

Have I decoded it correctly ?

**Comment by anutosh491** [comment] 2023-02-08 06:30
Also while trying out some cases , I realized `sep` and `end` keywords are not supported correctly in lpython (would like someone to confirm this) . I tried the following
```
(lf) anutosh491@spbhat68:~/lpython/lpython$ cat examples/expr2.py 
def main0():
    a: i32 = 1
    b: i32 = 2
    c: str = "abc"
    d: str = "def"
    e: list[i32] = [1, 2]
    f: list[i32] = [3, 4]
    print(a, b, sep = "pqr", end = "xyz")
    print(a, c, sep = "pqr", end = "xyz")
    print(c, d, sep = "pqr", end = "xyz")
    print(e, f, sep = "pqr", end = "xyz")

main0()
```
And got the following output
```
(lf) anutosh491@spbhat68:~/lpython/lpython$ ./src/bin/lpython examples/expr2.py
1 2
1 abc
abc def
[1, 2]
[3, 4]
```

It seems #687, #704 were meant to address these , so we might need to look into this too !

**Comment by anutosh491** [comment] 2023-02-08 13:10
> Also while trying out some cases , I realized sep and end keywords are not supported correctly in lpython (would like someone to confirm this)  

I tried to debug what might be going wrong here . I see that  `x.m_end` and `x.m_seperators` are not assigned to the correct values . 
https://github.com/lcompilers/lpython/blob/00ba081f0bf0bb52e9606ba7bfcbfbb0d195ff38/src/libasr/codegen/asr_to_llvm.cpp#L5796-L5813
Here if the program flow doesn't enter the `if(x.m_end)` block because `x.m_end` turns out to be `0` which is not expected . Hence we get use the default end keyword of newline . @Thirumalai-Shaktivel would be glad if you could guide me regarding these issues .

**Comment by Thirumalai-Shaktivel** [comment] 2023-02-08 14:00
https://github.com/lcompilers/lpython/issues/1477#issuecomment-1422050383
Yup, I think so.
 > The first line should be print(a, b, sep="pqr", end="") and not print(a, b, sep="pqr")

Yup, try to implement this and submit a PR, rest we will discuss there.

https://github.com/lcompilers/lpython/issues/1477#issuecomment-1422577267
There seem to be a bug in pass or ASR->LLVM that assign null to `x.end` and `x.sep`. We have to debug this.

**Comment by Thirumalai-Shaktivel** [comment] 2023-02-08 14:17
```py
print(a, b, l)
# becomes
print(a, b) # <-- change this to print(a, b, end="")
print("[", end="")
print(l.items, end="")
print("]", end="\n")
```
I think we have to handle this correctly inside this function:
https://github.com/lcompilers/lpython/blob/00ba081f0bf0bb52e9606ba7bfcbfbb0d195ff38/src/libasr/pass/print_list.cpp#L303

**Comment by Thirumalai-Shaktivel** [comment] 2023-02-08 14:41
https://github.com/lcompilers/lpython/issues/1477#issuecomment-1422577267
I see, here is the bug:
https://github.com/lcompilers/lpython/blob/00ba081f0bf0bb52e9606ba7bfcbfbb0d195ff38/src/libasr/pass/print_arr.cpp#L123-L125
We assign null to both `x.end` and `x.sep`, so the output.
@anutosh491 you can submit PRs for fixing this issues.
you understood how to fix them, right? Any doubts please ask.

**Comment by anutosh491** [comment] 2023-02-09 07:25
> I think we have to handle this correctly inside this function:
> https://github.com/lcompilers/lpython/blob/00ba081f0bf0bb52e9606ba7bfcbfbb0d195ff38/src/libasr/pass/print_list.cpp#L303

Yeah correct, I had analyzed this similarly ... I think it has something to do with this `make_Print_t` function
https://github.com/lcompilers/lpython/blob/00ba081f0bf0bb52e9606ba7bfcbfbb0d195ff38/src/libasr/pass/print_list.cpp#L312-L315

Here the last parameter passed shouldn't be a `nullptr` . That is being dealt as a newline .... we would just like to have a space there I guess . Could you help me like build an object of type `Print_t` such that it's end keyword is registered as a space (" "), something along these lines
```
expr_t *separator_expr = ASRUtils::EXPR(ASR::make_Const_t(al, x.base.base.loc, " "));
ASR::stmt_t *print_stmt = ASRUtils::STMT(
    ASR::make_Print_t(al, x.base.base.loc, nullptr, tmp_vec.p, tmp_vec.size(), x.m_separator, separator_expr));
```

I feel this would do the job for us !

**Comment by anutosh491** [comment] 2023-02-09 07:26
> We assign null to both `x.end` and `x.sep`, so the output.

Correct , once we address this , we've addressed the seperator and end issue .. I tried out some cases !

**Comment by anutosh491** [comment] 2023-02-09 08:28
The following diff somewhat explains what I'm trying to convey in the above comment (https://github.com/lcompilers/lpython/issues/1477#issuecomment-1423748579)
```
diff --git a/src/libasr/pass/print_list.cpp b/src/libasr/pass/print_list.cpp
index a4000f059..2a02c64e6 100644
--- a/src/libasr/pass/print_list.cpp
+++ b/src/libasr/pass/print_list.cpp
@@ -299,6 +299,10 @@ class PrintListVisitor
 
     void visit_Print(const ASR::Print_t &x) {
         std::vector<ASR::expr_t*> print_tmp;
+        ASR::ttype_t *str_type_len_1 = ASRUtils::TYPE(ASR::make_Character_t(
+        al, x.base.base.loc, 1, 1, nullptr, nullptr, 0));
+        ASR::expr_t *space = ASRUtils::EXPR(ASR::make_StringConstant_t(
+        al, x.base.base.loc, s2c(al, " "), str_type_len_1));
         for (size_t i=0; i<x.n_values; i++) {
             if (ASR::is_a<ASR::List_t>(*ASRUtils::expr_type(x.m_values[i])) ||
                 ASR::is_a<ASR::Tuple_t>(*ASRUtils::expr_type(x.m_values[i]))) {
@@ -310,13 +314,13 @@ class PrintListVisitor
                     }
                     ASR::stmt_t *print_stmt = ASRUtils::STMT(
                         ASR::make_Print_t(al, x.base.base.loc, nullptr, tmp_vec.p, tmp_vec.size(),
-                                    x.m_separator, nullptr));
+                                    x.m_separator, space));
                     print_tmp.clear();
                     pass_result.push_back(al, print_stmt);
 
                 }
                 if (ASR::is_a<ASR::List_t>(*ASRUtils::expr_type(x.m_values[i])))
-                    print_list_helper(x.m_values[i], x.m_separator, nullptr, x.base.base.loc);
+                    print_list_helper(x.m_values[i], x.m_separator, i == x.n_values - 1 ? nullptr : space, x.base.base.loc);
                 else
                     print_tuple_helper(x.m_values[i], x.m_separator, nullptr, x.base.base.loc);
                 for (size_t j=0; j<print_pass_result_tmp.n; j++)
```

After applying this diff , I get correct results for all of these cases 
```
def main1():
    a : i32 = 1
    l : list[i32] = [1,2,3]
    l2 : list[i32] = [4, 5, 6]
    s : str = "abc"
    print(a, l, s)
    print(l , a, s)
    print(a, s, l)

main1()
```
Output 
```
1 [1, 2, 3] abc
[1, 2, 3] 1 abc
1 abc [1, 2, 3]
```

**Comment by Thirumalai-Shaktivel** [comment] 2023-02-09 11:53
Great job, I think this would be correct fix.
Why don't you submit a PR with fixes and all the above tests in integration_tests?

**Comment by anutosh491** [comment] 2023-02-09 11:56
Sure, will do it soon ! Thanks for your review.

**Closed** 2023-02-26 17:16 UTC
